import 'server-only';
import {configured,publicDb,sessionDb} from './supabase';
import {type Entry,type Kind,type Resource,i18n,placeholder} from './domain';
import {officialAboutEntry} from './official-about';
import {officialContactEntry,officialDonationEntry} from './official-giving';
import {officialDigitisationEntries} from './official-digitisation';
import {localEntry,localLetter,localLetters} from './local-db';
export function defaults():Entry[]{const make=(kind:Kind,slug:string,title:Entry['title'],data:Entry['data']={},order=0):Entry=>({id:`00000000-0000-4000-8000-${String(order+1).padStart(12,'0')}`,kind,slug,title,description:kind==='settings'?i18n('神學教育服務團創立於2022年，支援不同宣教工場的神學教育。','Founded in 2022, TESC supports theological education in mission fields.'):placeholder,body:i18n('','',''),data,status:'published',published_at:'2020-01-01T00:00:00Z',display_order:order,featured:false,is_demo:true,is_private:false});return [make('settings','site',i18n('神學教育服務團','Theological Education Service Corps Ltd.','神学教育服务团'),{mission:i18n('透過神學教育裝備各地牧者與信徒領袖，協助他們廣傳福音、培育門徒、建立教會。','Equipping pastors and church leaders through theological education.')}),officialAboutEntry(),...officialDigitisationEntries(),...['Dr. Leung','Fai'].map((name,i)=>make('person',['leung','fai'][i],i18n(['梁家麟博士','吳健暉牧師'][i],name),{person_group:i===0?'board':'staff',role:i18n(['創辦人','總幹事'][i],['Founder','General Secretary'][i]),biography:i18n(['香港建道神學院榮休教授、榮譽院長，從事神學教育三十多年。','現任意大利華人神學院延伸部主任，任教實踐神學及教會歷史。'][i],['Professor emeritus at Alliance Bible Seminary with over 30 years in theological education.','Director of extension studies at the Chinese Theological Seminary in Italy.'][i])},20+i)),officialContactEntry(),officialDonationEntry()];}
export async function entries(kind?:Kind){if(!configured()){const letters=localLetters().map(p=>localEntry(p));return kind==='prayer'?letters:kind?defaults().filter(e=>e.kind===kind):[...defaults(),...letters];}let query=publicDb().from('public_content_entries').select('*').order('display_order').order('published_at',{ascending:false});if(kind)query=query.eq('kind',kind);const {data,error}=await query;if(error)throw new Error('Content unavailable');return data as Entry[];}
export async function entry(kind:Kind,slug:string){if(!configured()&&kind==='prayer'){const letter=localLetter(slug);return letter?localEntry(letter,true):undefined;}const teaser=(await entries(kind)).find(e=>e.slug===slug);if(!teaser?.is_private)return teaser;const db=await sessionDb();const {data:{user}}=await db.auth.getUser();if(!user)return teaser;const {data}=await db.from('content_entries').select('*').eq('kind',kind).eq('slug',slug).eq('status','published').lte('published_at',new Date().toISOString()).is('deleted_at',null).single();return (data as Entry)||teaser;}
export async function resources(){if(!configured())return [];const {data,error}=await publicDb().from('public_resources').select('*').order('created_at',{ascending:false});if(error)throw new Error('Resources unavailable');return data as Resource[];}
export const mediaUrl=(id:string|undefined|null,download=false)=>id?`/api/media/${id}${download?'?download=1':''}`:'';
