import {test,expect} from '@playwright/test';

test('prayer letters are public, sortable by date, and member sign-in works',async({page,request})=>{
 test.skip(!!process.env.NEXT_PUBLIC_SUPABASE_URL,'Local backend only');
 await page.goto('/zh-Hant/prayer');
 await expect(page.locator('.entry-card')).toHaveCount(9);
 await expect(page.locator('.entry-card').first()).toContainText('2026年9月');
 await expect(page.locator('.entry-card').last()).toContainText('2026年1月');
 await expect(page.getByRole('link',{name:'暉牧',exact:true})).toHaveCount(0);
 await page.getByRole('link',{name:'最舊至最新'}).click();
 await expect(page.locator('.entry-card').first()).toContainText('2026年1月');
 await expect(page.locator('.entry-card').last()).toContainText('2026年9月');
 await page.getByRole('link',{name:'最新至最舊'}).click();
 await page.getByRole('link',{name:/暉牧代禱信 · 2026年9月/}).click();
 const pdf=page.getByRole('link',{name:/查看 PDF/});await expect(pdf).toBeVisible();
 const pdfHref=await pdf.getAttribute('href')||'';
 const publicPdf=await request.get(pdfHref);
 expect(publicPdf.status()).toBe(200);expect(publicPdf.headers()['content-type']).toContain('application/pdf');
 expect((await publicPdf.body()).subarray(0,5).toString()).toBe('%PDF-');
 await page.goto('/signup');
 await page.getByLabel('姓名').fill('Prayer Reader');
 const email=`reader-${Date.now()}@example.test`;
 await page.getByLabel('電郵').fill(email);
 await page.getByLabel('密碼（至少 12 個字元）').fill('A-test-password-2026!');
 await page.getByLabel('確認密碼').fill('A-test-password-2026!');
 await page.getByRole('button',{name:'註冊'}).click();
 await expect(page).toHaveURL(/\/zh-Hant\/prayer/);
 await page.goto('/login');await page.getByRole('button',{name:'登出'}).click();
 await page.goto('/login');await page.getByLabel('電郵').fill(email);await page.getByLabel('密碼').fill('A-test-password-2026!');await page.getByRole('button',{name:'登入'}).click();
 await expect(page).toHaveURL(/\/zh-Hant\/prayer/);
 expect((await page.request.get(pdfHref)).status()).toBe(200);
});

test('local admin portal lists letters and publishes uploads',async({page,request})=>{
 test.skip(!process.env.TEST_LOCAL_ADMIN_EMAIL||!process.env.TEST_LOCAL_ADMIN_PASSWORD,'Admin credentials required');
 await page.goto('/admin/login');
 await page.getByLabel('電郵').fill(process.env.TEST_LOCAL_ADMIN_EMAIL!);
 await page.getByLabel('密碼').fill(process.env.TEST_LOCAL_ADMIN_PASSWORD!);
 await page.getByRole('button',{name:'登入'}).click();
 await expect(page).toHaveURL(/\/admin\?lang=zh-Hant/);
 await expect(page.getByRole('navigation',{name:'管理平台'})).toBeVisible();
 await page.getByRole('link',{name:'代禱信',exact:true}).click();
 await expect(page).toHaveURL(/\/admin\/prayer/);
 await page.getByRole('link',{name:'EN',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Prayer letter management'})).toBeVisible();
 await page.getByRole('link',{name:'繁',exact:true}).click();
 await expect(page.getByRole('heading',{name:'代禱信管理'})).toBeVisible();
 await expect(page.locator('.admin-table').first().locator('tbody tr')).toHaveCount(9);
 await page.getByLabel('標題').fill('測試代禱信');
 await page.getByLabel('發佈日期').fill('2026-10-01');
 await page.getByLabel('PDF 檔案').setInputFiles({name:'test.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\n1 0 obj\n<<>>\nendobj\n%%EOF')});
 await page.getByRole('button',{name:'上載並發佈'}).click(); await expect(page).toHaveURL(/message=/,{timeout:15000});
 await expect(page.getByText('代禱信已上載。')).toBeVisible();
 await expect(page.locator('.admin-table').first().locator('tbody tr')).toHaveCount(10);
 await expect(page.locator('.admin-table').first().locator('tbody tr').first()).toContainText('測試代禱信');
 const uploadedPdf=await page.locator('.admin-table').first().locator('tbody tr').first().getByRole('link',{name:'下載 PDF'}).getAttribute('href');
 expect((await request.get(uploadedPdf||'')).status()).toBe(200);
 await page.goto('/admin/prayer');
 page.once('dialog',dialog=>dialog.accept());
 await page.locator('.admin-table').first().locator('tbody tr').first().getByRole('button',{name:'移除'}).click();
 await expect(page.locator('.admin-table').first().locator('tbody tr')).toHaveCount(9);
});
