import Link from 'next/link';
import {notFound} from 'next/navigation';
import {ArrowUpRight,FileText,UserRound} from 'lucide-react';
import {entries,entry,resources,mediaUrl,defaults} from '@/lib/content';
import {type Locale,type Entry,translation,placeholder} from '@/lib/domain';
import {dict,date} from '@/lib/i18n';
import {seo} from '@/lib/seo';
import {PageHero,SectionTitle,Translated,Empty,EntryCard,Video} from '@/components/public';
import {PublicForm} from '@/components/public-form';
import {maxPublicBytes} from '@/lib/security';
const sections=['about','team','ministries','digitalisation','prayer','community','contact','courses'] as const;
type Params={locale:Locale;section:typeof sections[number]};
export async function generateMetadata({params}:{params:Promise<Params>}){const {locale,section}=await params;return seo(locale,`/${section}`,dict(locale)[section]);}
function Blocks({items,locale}:{items:Entry[];locale:Locale}){return <div className="editorial-blocks">{items.map((p,i)=><section key={p.id} className="editorial-block"><span className="block-number">{String(i+1).padStart(2,'0')}</span><div>{p.is_demo&&<span className="tag">PLACEHOLDER</span>}<h2><Translated value={p.title} locale={locale}/></h2><p><Translated value={p.description} locale={locale}/></p><Translated value={p.body} locale={locale} rich/>{p.data.image_id&&<img loading="lazy" src={mediaUrl(p.data.image_id)} alt={translation(p.title,locale).text}/>}<Translated value={p.data.quote} locale={locale} rich/>{p.data.timeline_date&&<p>{p.data.timeline_date}</p>}{p.data.statistic_value&&<strong className="statistic">{p.data.statistic_value}</strong>}{p.data.pdf_id&&<Link href={mediaUrl(p.data.pdf_id)} className="text-link">{dict(locale).view} PDF ↗</Link>}</div></section>)}</div>}
export default async function Section({params,searchParams}:{params:Promise<Params>;searchParams:Promise<{author?:string;category?:string}>}){const {locale,section}=await params;if(!sections.includes(section))notFound();const d=dict(locale),query=await searchParams;
 if(section==='about'){const stored=await entries('page');const items=stored.length?stored:defaults().filter(e=>e.kind==='page');return <main id="main"><PageHero eyebrow="ABOUT TESC" title={d.aboutIntro}/><div className="wrap content-with-aside"><aside><p className="eyebrow">TESC</p><Link href={`/${locale}/team`}>{d.team}<ArrowUpRight size={17}/></Link></aside><Blocks items={items} locale={locale}/></div></main>;}
 if(section==='team'){const stored=await entries('person');const people=stored.length?stored:defaults().filter(e=>e.kind==='person');return <main id="main"><PageHero eyebrow="OUR PEOPLE" title={d.team}/><div className="wrap section">{(['board','staff'] as const).map(group=><section key={group} className="people-section"><h2>{d[group]}</h2><div className="people-grid">{people.filter(p=>p.data.person_group===group).map(p=><article key={p.id} className="person">{p.data.image_id?<img src={mediaUrl(p.data.image_id)} alt={translation(p.title,locale).text}/>:<div className="portrait-placeholder"><UserRound size={40} strokeWidth={1}/></div>}<h3><Translated value={p.title} locale={locale}/></h3><p><Translated value={p.data.role} locale={locale}/></p><p><Translated value={p.data.biography||p.description} locale={locale}/></p><Translated value={p.body} locale={locale} rich/><p><Translated value={p.data.responsibilities} locale={locale}/></p>{p.data.email&&<a href={`mailto:${p.data.email}`}>{p.data.email}</a>}</article>)}</div></section>)}</div></main>;}
 if(section==='ministries'||section==='courses'){const [ministries,courses,videos]=await Promise.all([entries('ministry'),entries('course'),entries('video')]);return <main id="main"><PageHero eyebrow="EDUCATION & SERVICE" title={section==='courses'?d.courses:d.ministryIntro}/><div className="wrap section">{section==='ministries'&&<><div className="video-feature"><div><p className="eyebrow">TESC IN MINISTRY</p><h2>{d.video}</h2><p>{d.placeholder}</p></div><Video item={videos[0]} locale={locale}/></div><SectionTitle title={d.ministries}/>{ministries.length?<div className="cards three">{ministries.map(p=><EntryCard key={p.id} item={p} locale={locale} base={`/${locale}/ministries`}/>)}</div>:<Empty>{d.placeholder}</Empty>}</>}<section id="courses" className="course-section"><SectionTitle title={d.courses}/>{courses.length?<div className="cards three">{courses.map(p=><EntryCard key={p.id} item={p} locale={locale} base={`/${locale}/courses`}/>)}</div>:<Empty>{d.emptyCourse}</Empty>}</section></div></main>;}
 if(section==='digitalisation'){const [projects,blocks,docs]=await Promise.all([entries('project'),entries('project_section'),entries('project_document')]);return <main id="main"><PageHero eyebrow="CHINESE CHURCH HISTORY DIGITISATION PROJECT" title={d.digitalisation} description={d.archiveIntro} archive/><div className="wrap section"><div className="project-intro"><img src="/images/archival-hero.webp" alt={d.illustration}/><div><p className="eyebrow">PRESERVATION & MEMORY</p><h2>{d.archiveIntro}</h2><p><Translated value={projects[0]?.description||placeholder} locale={locale}/></p><Translated value={projects[0]?.body} locale={locale} rich/><small className="muted">{d.illustration}</small></div></div><Blocks items={blocks} locale={locale}/>{docs.length>0&&<section className="section"><h2>{locale==='en'?'Selected documents':locale==='zh-Hans'?'精选文献':'精選文獻'}</h2><Blocks items={docs} locale={locale}/></section>}<Link className="button" href={`/${locale}/contact#giving`}>{d.giving}<ArrowUpRight size={18}/></Link></div></main>;}
 if(section==='prayer'){let letters=await entries('prayer');letters=letters.filter(p=>!query.author||p.data.author===query.author).sort((a,b)=>Date.parse(b.published_at!)-Date.parse(a.published_at!));return <main id="main"><PageHero eyebrow="LETTERS & PRAYER" title={d.prayer} description={d.prayerIntro}/><div className="wrap section"><nav className="filter-tabs" aria-label={d.prayer}>{['','暉牧','JOYCE LOK'].map(author=><Link key={author} aria-current={(query.author||'')===author?'page':undefined} href={`/${locale}/prayer${author?`?author=${encodeURIComponent(author)}`:''}`}>{author||d.all}</Link>)}</nav>{letters.length?<div className="cards three">{letters.map(p=><EntryCard key={p.id} item={p} locale={locale} base={`/${locale}/prayer`}/>)}</div>:<Empty icon="file">{d.emptyPrayer}</Empty>}</div></main>;}
 if(section==='community'){const [items,categories,settings]=await Promise.all([resources(),entries('resource_category'),entry('settings','site')]);const visible=items.filter(p=>!query.category||p.category===query.category);return <main id="main"><PageHero eyebrow="COMMUNITY RESOURCES" title={translation(settings?.data.resource_label,locale).text||d.community} description={d.resourcesIntro}/><div className="wrap section"><div className="section-title"><nav className="filter-tabs" aria-label={d.category}><Link href={`/${locale}/community`} aria-current={!query.category?'page':undefined}>{d.all}</Link>{categories.map(c=><Link key={c.id} href={`/${locale}/community?category=${c.slug}`} aria-current={query.category===c.slug?'page':undefined}><Translated value={c.title} locale={locale}/></Link>)}</nav><a className="button secondary" href="#submit">{d.upload}<ArrowUpRight size={18}/></a></div>{visible.length?<div className="resource-list">{visible.map(r=><article key={r.id}><FileText size={28}/><div><h3><Translated value={r.title} locale={locale}/></h3><p><Translated value={r.description} locale={locale}/></p><span className="meta">PDF · {(r.file_size/1024/1024).toFixed(1)} MB · {date(r.created_at,locale)}</span></div><div className="resource-actions"><a className="text-link" href={mediaUrl(r.media_id)} target="_blank" rel="noreferrer">{d.view} ↗</a><a className="text-link" href={mediaUrl(r.media_id,true)}>{d.download} ↓</a></div></article>)}</div>:<Empty icon="file">{d.emptyResource}</Empty>}<section id="submit" className="submission-section"><div><p className="eyebrow">SHARE WITH THE COMMUNITY</p><h2>{d.upload}</h2><p className="muted">{d.pending}</p></div><PublicForm type="resource" locale={locale} siteKey={process.env.CLOUDFLARE_TURNSTILE_SITE_KEY||''} limit={maxPublicBytes()/1024/1024} categories={categories.map(c=>({id:c.slug,label:translation(c.title,locale).text}))}/></section></div></main>;}
 const [contact,donation]=await Promise.all([entry('contact','contact'),entry('donation','default')]);return <main id="main"><PageHero eyebrow="CONTACT & GIVING" title={d.contact}/><div className="wrap section"><div className="contact-grid"><section><p className="eyebrow">GET IN TOUCH</p><h2>{d.contactUs}</h2><p>{d.rights}</p><p><Translated value={contact?.data.address||placeholder} locale={locale}/></p>{contact?.data.email&&<p><a href={`mailto:${contact.data.email}`}>{contact.data.email}</a></p>}{contact?.data.phone&&<p>{contact.data.phone}</p>}{contact?.data.whatsapp&&<p>WhatsApp: {contact.data.whatsapp}</p>}{contact?.data.social_url&&<a className="text-link" href={contact.data.social_url}>Social ↗</a>}<Translated value={contact?.body} locale={locale} rich/></section><PublicForm type="contact" locale={locale} siteKey={process.env.CLOUDFLARE_TURNSTILE_SITE_KEY||''}/></div><section id="giving" className="giving-panel"><div><p className="eyebrow">PRAYER & PARTNERSHIP</p><h2>{d.giving}</h2></div><div><h3>{donation?<Translated value={donation.title} locale={locale}/>:locale==='en'?'[Awaiting donation instructions]':locale==='zh-Hans'?'[待输入奉献方式]':'[待輸入奉獻方式]'}</h3><p><Translated value={donation?.description} locale={locale}/></p><Translated value={donation?.body} locale={locale} rich/>{donation?.data.account_name&&<p>{donation.data.account_name}</p>}{donation?.data.bank_info&&<p style={{whiteSpace:'pre-wrap'}}>{donation.data.bank_info}</p>}{donation?.data.qr_id&&<img className="qr" alt={d.giving} src={mediaUrl(donation.data.qr_id)}/>}<p><Translated value={donation?.data.notes} locale={locale}/></p>{donation?.data.donation_url&&<a href={donation.data.donation_url} className="text-link">{d.learn} ↗</a>}</div></section></div></main>;
}
