import Link from 'next/link';
import {notFound,permanentRedirect} from 'next/navigation';
import {ArrowUpRight,UserRound} from 'lucide-react';
import {entries,entry,mediaUrl,defaults} from '@/lib/content';
import {type Locale,type Entry,translation} from '@/lib/domain';
import {dict} from '@/lib/i18n';
import {seo} from '@/lib/seo';
import {PageHero,SectionTitle,Translated,Empty,EntryCard} from '@/components/public';
import {PosterGallery} from '@/components/poster-gallery';
import {aboutDescription} from '@/lib/official-about';
const sections=['about','team','ministries','digitalisation','prayer','community','contact','courses'] as const;
type Params={locale:Locale;section:typeof sections[number]};
export async function generateMetadata({params}:{params:Promise<Params>}){const {locale,section}=await params;return seo(locale,`/${section}`,dict(locale)[section]);}
function Blocks({items,locale}:{items:Entry[];locale:Locale}){return <div className="editorial-blocks">{items.map((p,i)=><section key={p.id} className="editorial-block"><span className="block-number">{String(i+1).padStart(2,'0')}</span><div>{p.is_demo&&<span className="tag">PLACEHOLDER</span>}<h2><Translated value={p.title} locale={locale}/></h2>{translation(p.description,locale).text&&<p><Translated value={p.description} locale={locale}/></p>}<Translated value={p.body} locale={locale} rich/>{p.data.image_id&&<img loading="lazy" src={mediaUrl(p.data.image_id)} alt={translation(p.title,locale).text}/>}<Translated value={p.data.quote} locale={locale} rich/>{p.data.timeline_date&&<p>{p.data.timeline_date}</p>}{p.data.statistic_value&&<strong className="statistic">{p.data.statistic_value}</strong>}{p.data.pdf_id&&<Link href={mediaUrl(p.data.pdf_id)} className="text-link">{dict(locale).view} PDF ↗</Link>}</div></section>)}</div>}
export default async function Section({params,searchParams}:{params:Promise<Params>;searchParams:Promise<{sort?:string}>}){const {locale,section}=await params;if(!sections.includes(section))notFound();const d=dict(locale),query=await searchParams;
 if(section==='about'){const stored=await entries('page');const items=stored.length?stored:defaults().filter(e=>e.kind==='page');return <main id="main"><PageHero eyebrow="ABOUT TESC" title={d.aboutIntro} description={translation(aboutDescription,locale).text}/><div className="wrap content-with-aside"><aside><p className="eyebrow">TESC</p><Link href={`/${locale}/team`}>{d.team}<ArrowUpRight size={17}/></Link></aside><Blocks items={items} locale={locale}/></div></main>;}
 if(section==='team'){const stored=await entries('person');const people=stored.length?stored:defaults().filter(e=>e.kind==='person');return <main id="main"><PageHero eyebrow="OUR PEOPLE" title={d.team}/><div className="wrap section">{(['board','staff'] as const).map(group=><section key={group} className="people-section"><h2>{d[group]}</h2><div className="people-grid">{people.filter(p=>p.data.person_group===group).map(p=><article key={p.id} className="person">{p.data.image_id?<img src={mediaUrl(p.data.image_id)} alt={translation(p.title,locale).text}/>:["leung","fai"].includes(p.slug)?<img src={`/images/${p.slug==="leung"?"dr-leung":"fai"}.avif`} alt={translation(p.title,locale).text}/>:<div className="portrait-placeholder"><UserRound size={40} strokeWidth={1}/></div>}<h3><Translated value={p.title} locale={locale}/></h3><p><Translated value={p.data.role} locale={locale}/></p><p><Translated value={p.data.biography||p.description} locale={locale}/></p><Translated value={p.body} locale={locale} rich/><p><Translated value={p.data.responsibilities} locale={locale}/></p>{p.data.email&&<a href={`mailto:${p.data.email}`}>{p.data.email}</a>}</article>)}</div></section>)}</div></main>;}
 if(section==='courses')permanentRedirect('/'+locale+'/ministries#courses');
 if(section==='ministries'){
  const courses=await entries('course');
  return <main id="main" className="course-page"><PageHero eyebrow="EDUCATION & SERVICE" title={d.ministries} description={locale==='en'?'Explore the course pathway, individual subjects and TESC’s ministry work.':locale==='zh-Hans'?'认识课程架构、各科内容与神学教育服务团的事工。':'認識課程架構、各科內容與神學教育服務團的事工。'}/><div className="wrap section"><PosterGallery locale={locale}/>{courses.length>0&&<section className="admin-courses"><SectionTitle title={locale==='en'?'More course updates':locale==='zh-Hans'?'更多课程资讯':'更多課程資訊'}/><div className="cards three">{courses.map(p=><EntryCard key={p.id} item={p} locale={locale} base={'/'+locale+'/courses'}/>)}</div></section>}</div></main>;
 }
 if(section==='digitalisation'){
  const [projects,blocks,docs]=await Promise.all([entries('project'),entries('project_section'),entries('project_document')]);
  const project=projects.find(item=>item.slug==='first-stage-plan')||projects[0];
  return <main id="main"><PageHero eyebrow="CHINESE CHURCH HISTORY DIGITISATION PROJECT" title={d.digitalisation} description={translation(project?.description,locale).text||d.archiveIntro} archive/><div className="wrap section"><div className="project-intro plan-intro"><div><p className="eyebrow">{locale==='en'?'STAGE ONE PROPOSAL · 31 JULY 2026':locale==='zh-Hans'?'第一阶段计划书 · 2026年7月31日':'第一階段計劃書 · 2026年7月31日'}</p><h2><Translated value={project?.title} locale={locale}/></h2><Translated value={project?.body} locale={locale} rich/></div></div><Blocks items={blocks} locale={locale}/>{docs.length>0&&<section className="section"><h2>{locale==='en'?'Selected documents':locale==='zh-Hans'?'精选文献':'精選文獻'}</h2><div className="cards three">{docs.map(doc=><EntryCard key={doc.id} item={doc} locale={locale} base={'/'+locale+'/digitalisation'}/>)}</div></section>}<Link className="button" href={'/'+locale+'/contact#giving'}>{d.giving}<ArrowUpRight size={18}/></Link></div></main>;
 }
 if(section==='prayer'){const oldest=query.sort==='oldest';const letters=(await entries('prayer')).sort((a,b)=>(oldest?1:-1)*(Date.parse(a.published_at||'')-Date.parse(b.published_at||'')));return <main id="main"><PageHero eyebrow="LETTERS & PRAYER" title={d.prayer} description={d.prayerIntro}/><div className="wrap section"><nav className="filter-tabs" aria-label={locale==='en'?'Sort by date':locale==='zh-Hans'?'按日期排序':'按日期排序'}><Link aria-current={!oldest?'page':undefined} href={`/${locale}/prayer`}>{locale==='en'?'Newest to oldest':locale==='zh-Hans'?'最新到最旧':'最新至最舊'}</Link><Link aria-current={oldest?'page':undefined} href={`/${locale}/prayer?sort=oldest`}>{locale==='en'?'Oldest to newest':locale==='zh-Hans'?'最旧到最新':'最舊至最新'}</Link></nav>{letters.length?<div className="cards three">{letters.map(p=><EntryCard key={p.id} item={p} locale={locale} base={`/${locale}/prayer`}/>)}</div>:<Empty icon="file">{d.emptyPrayer}</Empty>}</div></main>;}
 if(section==='community')permanentRedirect('/'+locale+'/ministries#posters');
 const [contact,donation]=await Promise.all([entry('contact','contact'),entry('donation','default')]);return <main id="main"><PageHero eyebrow="CONTACT & GIVING" title={d.contact}/><div className="wrap section"><div className="contact-details"><section><p className="eyebrow">GET IN TOUCH</p><h2>{d.contactUs}</h2><p>{d.rights}</p>{contact?.data.address&&<p><Translated value={contact.data.address} locale={locale}/></p>}{contact?.data.email&&<p><a href={`mailto:${contact.data.email}`}>{contact.data.email}</a></p>}{contact?.data.phone&&<p>{contact.data.phone}</p>}{contact?.data.whatsapp&&<p>WhatsApp: {contact.data.whatsapp}</p>}{contact?.data.social_url&&<a className="text-link" href={contact.data.social_url}>Social ↗</a>}<Translated value={contact?.body} locale={locale} rich/></section></div><section id="giving" className="giving-panel"><div><p className="eyebrow">PRAYER & PARTNERSHIP</p><h2>{d.giving}</h2></div><div><h3>{donation?<Translated value={donation.title} locale={locale}/>:locale==='en'?'[Awaiting donation instructions]':locale==='zh-Hans'?'[待输入奉献方式]':'[待輸入奉獻方式]'}</h3><p><Translated value={donation?.description} locale={locale}/></p><Translated value={donation?.body} locale={locale} rich/>{donation?.data.account_name&&<p>{donation.data.account_name}</p>}{donation?.data.bank_info&&<p style={{whiteSpace:'pre-wrap'}}>{donation.data.bank_info}</p>}{donation?.data.qr_id&&<img className="qr" alt={d.giving} src={mediaUrl(donation.data.qr_id)}/>}<p><Translated value={donation?.data.notes} locale={locale}/></p>{donation?.data.donation_url&&<a href={donation.data.donation_url} className="text-link">{d.learn} ↗</a>}</div></section></div></main>;
}
