import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import {beforeAll,afterAll,describe,it,expect} from 'vitest';
let db:PGlite;
const editor='00000000-0000-4000-8000-000000000001',admin='00000000-0000-4000-8000-000000000002';
async function as(role:string,id:string,sql:string){await db.exec(`set role ${role}; select set_config('request.jwt.claim.sub','${id}',false);`);try{return await db.query(sql);}finally{await db.exec('reset role');}}
beforeAll(async()=>{db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to anon,authenticated,service_role;grant execute on function auth.uid() to anon,authenticated,service_role;create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);alter table storage.objects enable row level security;grant usage on schema storage to anon,authenticated;grant all on storage.objects to anon,authenticated;create policy existing_broad on storage.objects for all to anon,authenticated using(true) with check(true);`);await db.exec(readFileSync('supabase/migrations/202609280001_foundation.sql','utf8'));await db.exec(`insert into auth.users values('${editor}'),('${admin}');insert into profiles(id,role) values('${editor}','editor'),('${admin}','super_admin');`);});
afterAll(async()=>await db.close());
describe.sequential('real PostgreSQL schema and RLS',()=>{
 it('applies migrations and draft demo seed',async()=>{await db.exec(readFileSync('supabase/seed.sql','utf8'));const result=await as('anon','',`select * from content_entries`);expect(result.rows).toHaveLength(0);});
 it('public only sees published records whose UTC time has arrived',async()=>{await db.exec(`insert into content_entries(kind,slug,status,published_at) values('prayer','past','published',now()-interval '1 minute'),('prayer','future','published',now()+interval '1 day'),('prayer','draft','draft',now()-interval '1 day');`);const result=await as('anon','',`select slug from content_entries`);expect(result.rows).toEqual([{slug:'past'}]);await db.exec(`update content_entries set published_at=now()-interval '1 second' where slug='future'`);expect((await as('anon','',`select slug from content_entries order by slug`)).rows).toEqual([{slug:'future'},{slug:'past'}]);});
 it('anonymous cannot write content or read private submissions',async()=>{await expect(as('anon','',`insert into content_entries(kind,slug) values('page','hacked')`)).rejects.toThrow();await expect(as('anon','',`select contributor_email from community_resources`)).rejects.toThrow();await expect(as('anon','',`select * from contact_submissions`)).rejects.toThrow();});
 it('authenticated non-admin cannot edit content',async()=>{await expect(as('authenticated','00000000-0000-4000-8000-000000000003',`insert into content_entries(kind,slug) values('page','hacked')`)).rejects.toThrow();});
 it('editor can edit prayer letters but not site settings or own role',async()=>{await as('authenticated',editor,`insert into content_entries(kind,slug,created_by) values('prayer','editor-letter','${editor}')`);await expect(as('authenticated',editor,`insert into content_entries(kind,slug) values('settings','other')`)).rejects.toThrow();await as('authenticated',editor,`update profiles set role='super_admin' where id='${editor}'`);expect((await db.query(`select role from profiles where id='${editor}'`)).rows).toEqual([{role:'editor'}]);});
 it('super admin can manage settings and roles',async()=>{await as('authenticated',admin,`insert into content_entries(kind,slug) values('settings','additional')`);expect((await as('authenticated',admin,`select * from profiles`)).rows.length).toBe(2);});
 it('public resources require moderation and clean media; safe view omits email',async()=>{await db.exec(`insert into media_items(id,original_name,path,mime_type,file_size) values('00000000-0000-4000-8000-000000000010','test.pdf','test.pdf','application/pdf',50);insert into community_resources(id,title,description,media_id,file_size,contributor_email) values('00000000-0000-4000-8000-000000000011','{"en":"Test"}','{}','00000000-0000-4000-8000-000000000010',50,'private@example.org');`);expect((await as('anon','',`select * from public_resources`)).rows).toHaveLength(0);await expect(as('authenticated',editor,`update community_resources set status='approved',published=true,scan_status='clean'`)).rejects.toThrow();await db.exec(`update media_items set scan_status='clean'`);await as('authenticated',editor,`update community_resources set status='approved',published=true,scan_status='clean'`);const rows=(await as('anon','',`select * from public_resources`)).rows;expect(rows).toHaveLength(1);expect(rows[0]).not.toHaveProperty('contributor_email');await as('authenticated',editor,`update community_resources set status='hidden'`);expect((await as('anon','',`select * from public_resources`)).rows).toHaveLength(0);});
 it('anonymous cannot modify another resource and editor cannot forge media scan',async()=>{await expect(as('anon','',`update community_resources set status='approved'`)).rejects.toThrow();await expect(as('authenticated',editor,`update media_items set scan_status='clean'`)).rejects.toThrow();});
 it('atomic persistent limits enforce count and byte quota',async()=>{expect((await db.query(`select consume_limit('test',2,3600,10,30) as ok`)).rows).toEqual([{ok:true}]);expect((await db.query(`select consume_limit('test',2,3600,10,30) as ok`)).rows).toEqual([{ok:true}]);expect((await db.query(`select consume_limit('test',2,3600,10,30) as ok`)).rows).toEqual([{ok:false}]);await expect(as('anon','',`select consume_limit('bypass',1000,1,0,1000)`)).rejects.toThrow();});
 it('all storage buckets are private and direct object access is blocked',async()=>{await db.exec("insert into storage.objects(bucket_id,name) values('admin-media','secret.pdf')");expect((await as('anon','',"select * from storage.objects")).rows).toHaveLength(0);await expect(as('authenticated',editor,"insert into storage.objects(bucket_id,name) values('admin-media','forged.pdf')")).rejects.toThrow();expect((await db.query(`select count(*)::int as n from storage.buckets where public=true`)).rows).toEqual([{n:0}]);});
});
