import {describe,it,expect,vi,afterEach} from 'vitest';
vi.mock('../src/lib/supabase',()=>({serviceDb:vi.fn(),configured:()=>false,sessionDb:vi.fn()}));
import {limitedForm,captcha,publicGuard,scan} from '../src/lib/security';
import {sameOrigin} from '../src/lib/auth';
import {serviceDb} from '../src/lib/supabase';
afterEach(()=>{vi.unstubAllEnvs();vi.unstubAllGlobals();vi.resetAllMocks();});
describe('public request protection',()=>{
 it('rejects cross-origin and absent origin requests',()=>{vi.stubEnv('NEXT_PUBLIC_SITE_URL','https://tesc.org.hk');expect(()=>sameOrigin(new Request('https://tesc.org.hk/api/contact',{headers:{origin:'https://evil.test'}}))).toThrow();expect(()=>sameOrigin(new Request('https://tesc.org.hk/api/contact'))).toThrow();expect(()=>sameOrigin(new Request('https://tesc.org.hk/api/contact',{headers:{origin:'https://tesc.org.hk'}}))).not.toThrow();});
 it('enforces actual streamed body length without trusting Content-Length',async()=>{const stream=new ReadableStream({start(controller){controller.enqueue(new Uint8Array(1000));controller.close();}});const request=new Request('http://localhost',{method:'POST',body:stream,duplex:'half'} as RequestInit);await expect(limitedForm(request,100)).rejects.toMatchObject({status:413});});
 it('fails closed without Turnstile configuration',async()=>{vi.stubEnv('CLOUDFLARE_TURNSTILE_SECRET_KEY','');await expect(captcha(new FormData(),'resource')).rejects.toMatchObject({status:503});});
 it('checks CAPTCHA result, hostname and action',async()=>{vi.stubEnv('CLOUDFLARE_TURNSTILE_SECRET_KEY','test-secret');vi.stubEnv('NEXT_PUBLIC_SITE_URL','https://tesc.org.hk');const form=new FormData();form.set('cf-turnstile-response','test-token');const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);for(const result of [{success:false},{success:true,hostname:'evil.test',action:'resource'},{success:true,hostname:'tesc.org.hk',action:'contact'}]){fetcher.mockResolvedValue({json:async()=>result});await expect(captcha(form,'resource')).rejects.toMatchObject({status:400});}fetcher.mockResolvedValue({json:async()=>({success:true,hostname:'tesc.org.hk',action:'resource'})});await expect(captcha(form,'resource')).resolves.toBeUndefined();});
 it('rejects honeypot submissions',async()=>{const form=new FormData();form.set('website','spam');await expect(captcha(form,'contact')).rejects.toMatchObject({status:400});});
 it('rate limits using hashed identifiers and never trusts forwarded IP by default',async()=>{vi.stubEnv('NEXT_PUBLIC_SITE_URL','https://tesc.org.hk');vi.stubEnv('RATE_LIMIT_SECRET','long-secret');vi.stubEnv('TRUST_CLOUDFLARE','false');const rpc=vi.fn().mockResolvedValue({data:true});vi.mocked(serviceDb).mockReturnValue({rpc} as unknown as ReturnType<typeof serviceDb>);await publicGuard(new Request('https://tesc.org.hk/api/resources',{headers:{origin:'https://tesc.org.hk','cf-connecting-ip':'192.0.2.1'}}),'resource',100);expect(rpc.mock.calls[0][1].p_key).toMatch(/^[a-f0-9]{64}$/);rpc.mockResolvedValue({data:false});await expect(publicGuard(new Request('https://tesc.org.hk/api/resources',{headers:{origin:'https://tesc.org.hk'}}),'resource')).rejects.toMatchObject({status:429});});
 it('scan adapter never treats an unavailable or unrecognized scanner as clean',async()=>{vi.stubEnv('MALWARE_SCAN_URL','');expect(await scan(new Uint8Array(),'application/pdf')).toBe('pending');vi.stubEnv('MALWARE_SCAN_URL','https://scanner.example.test');vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({status:'unknown'})}));expect(await scan(new Uint8Array(),'application/pdf')).toBe('error');vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({status:'infected'})}));expect(await scan(new Uint8Array(),'application/pdf')).toBe('infected');});
});
