import {notFound} from 'next/navigation';
import Link from 'next/link';
import {entry,entries,mediaUrl} from '@/lib/content';
import {type Locale,type Kind,translation} from '@/lib/domain';
import {dict,date} from '@/lib/i18n';
import {seo} from '@/lib/seo';
import {Translated,Video,EntryCard} from '@/components/public';
type Params={locale:Locale;section:string;slug:string};
const kind=(s:string):Kind|undefined=>({prayer:'prayer',ministries:'ministry',courses:'course'} as Record<string,Kind>)[s];
export async function generateMetadata({params}:{params:Promise<Params>}){const p=await params,k=kind(p.section);if(!k)return {};const item=await entry(k,p.slug);if(!item)return {};return seo(p.locale,`/${p.section}/${p.slug}`,translation(item.title,p.locale).text,item);}
export default async function Detail({params}:{params:Promise<Params>}){const {locale,section,slug}=await params,k=kind(section);if(!k)notFound();const p=await entry(k,slug);if(!p)notFound();const d=dict(locale),all=k==='prayer'?await entries('prayer'):[];all.sort((a,b)=>Date.parse(b.published_at!)-Date.parse(a.published_at!));const index=all.findIndex(e=>e.id===p.id);const related=k==='ministry'?(await entries('course')).filter(c=>p.data.related_ids?.includes(c.id)):[];return <main id="main" className="article-main wrap"><Link href={`/${locale}/${section}`} className="text-link">← {d.back}</Link><header className="article-heading">{p.is_demo&&<span className="tag">DEMO / PLACEHOLDER</span>}<p className="eyebrow">{k==='prayer'?`${p.data.author||''} · ${date(p.published_at!,locale)}`:'TESC'}</p><h1><Translated value={p.title} locale={locale}/></h1><p className="lead"><Translated value={p.description} locale={locale}/></p></header>{p.data.image_id&&<img className="article-cover" src={mediaUrl(p.data.image_id)} alt={translation(p.title,locale).text}/>}<div className="article-body"><Translated value={p.body} locale={locale} rich/>{['subtitle','objectives','audience','lecturer','format','duration','credits'].map(field=>{const value=p.data[field as keyof typeof p.data];return value&&typeof value==='object'&&!Array.isArray(value)?<section key={field}><h2>{locale==='en'?field:{subtitle:'副標題',objectives:'學習目標',audience:'對象',lecturer:'講師',format:'形式',duration:'時數',credits:'學分資料'}[field]}</h2><Translated value={value} locale={locale}/></section>:null;})}{p.data.video_id&&<Video item={{...p,data:{...p.data,source_type:'upload'}}} locale={locale}/>}<div className="article-actions">{p.data.pdf_id&&<><a className="button secondary" href={mediaUrl(p.data.pdf_id)}>{d.view} PDF ↗</a><a className="text-link" href={mediaUrl(p.data.pdf_id,true)}>{d.download} PDF ↓</a></>}{p.data.registration_url&&<a className="button" href={p.data.registration_url}>{locale==='en'?'Registration information':'報名資料'} ↗</a>}{p.data.cta_url&&<a className="text-link" href={p.data.cta_url}><Translated value={p.data.cta_label} locale={locale}/> ↗</a>}</div>{k==='prayer'&&<nav className="letter-navigation">{all[index+1]&&<Link href={`/${locale}/prayer/${all[index+1].slug}`}>← {d.previous}</Link>}{all[index-1]&&<Link href={`/${locale}/prayer/${all[index-1].slug}`}>{d.next} →</Link>}</nav>}</div>{related.length>0&&<section className="section"><h2>{d.courses}</h2><div className="cards three">{related.map(c=><EntryCard key={c.id} item={c} locale={locale} base={`/${locale}/courses`}/>)}</div></section>}</main>}
