'use server';
import {redirect} from 'next/navigation';
import {sessionDb,configured} from '@/lib/supabase';
import {identity} from '@/lib/auth';
import {z} from 'zod';
import {localAuthenticate,localDb,hashPassword} from '@/lib/local-db';
import {localIdentity,localSignIn,localSignOut} from '@/lib/local-auth';
import {adminLocale} from '@/lib/admin-i18n';
export async function login(form:FormData){const email=String(form.get('email')||''),password=String(form.get('password')||''),locale=adminLocale(String(form.get('lang')||''));if(!z.email().safeParse(email).success||password.length<8)redirect(`/admin/login?lang=${locale}&error=login`);if(!configured()){const actor=localAuthenticate(email,password);if(!actor)redirect(`/admin/login?lang=${locale}&error=login`);await localSignIn(actor.id);redirect(actor.role==='member'?`/${locale}/prayer`:`/admin?lang=${locale}`);}const db=await sessionDb();const {error}=await db.auth.signInWithPassword({email,password});if(error)redirect(`/admin/login?lang=${locale}&error=login`);const actor=await identity();if(!actor){await db.auth.signOut();redirect(`/admin/login?lang=${locale}&error=forbidden`);}if(actor.role==='member')redirect(`/${locale}/prayer`);redirect(`/admin?lang=${locale}`);}
export async function logout(){if(configured())await (await sessionDb()).auth.signOut();else await localSignOut();redirect('/admin/login');}
export async function resetPassword(form:FormData){const locale=adminLocale(String(form.get('lang')||''));if(!configured())redirect(`/admin/login?lang=${locale}&error=config`);const email=String(form.get('email')||'');if(z.email().safeParse(email).success){await (await sessionDb()).auth.resetPasswordForEmail(email,{redirectTo:`${process.env.NEXT_PUBLIC_SITE_URL}/auth/confirm?next=/admin/password`});}redirect(`/admin/login?lang=${locale}&message=reset`);}
export async function updatePassword(form:FormData){const password=String(form.get('password')||''),locale=adminLocale(String(form.get('lang')||''));if(password.length<12||password.length>200||password!==form.get('confirm'))redirect(`/admin/password?lang=${locale}&error=password`);if(!configured()){const user=await localIdentity();if(!user)redirect('/admin/login');localDb().prepare('update users set password_hash=? where id=?').run(hashPassword(password),user.id);redirect(user.role==='member'?`/${locale}/prayer`:`/admin/account?lang=${locale}&message=password`);}const user=await identity();if(!user)redirect('/admin/login');const {error}=await user.db.auth.updateUser({password});if(error)redirect(`/admin/password?lang=${locale}&error=password`);redirect(user.role==='member'?`/${locale}/prayer`:`/admin?lang=${locale}&message=password`);}
