import {redirect} from 'next/navigation';
import Link from 'next/link';
import {identity} from '@/lib/auth';
import {AdminShell} from '@/components/admin-shell';
import {configured} from '@/lib/supabase';
import {localIdentity} from '@/lib/local-auth';
import {LocalAdmin} from '@/components/local-admin';
import {adminLocale} from '@/lib/admin-i18n';
export const metadata={title:'TESC 管理總覽',robots:{index:false,follow:false}};
export default async function Admin({searchParams}:{searchParams:Promise<{message?:string;lang?:string}>}){if(!configured()){const actor=await localIdentity();if(!actor||actor.role!=='super_admin')redirect('/admin/login');const query=await searchParams;return <LocalAdmin module="dashboard" actor={actor} locale={adminLocale(query.lang)} message={query.message}/>;}const actor=await identity();if(!actor||actor.role==='member')redirect('/admin/login');const [{count:pending},{count:scheduled},{count:contacts}]=await Promise.all([actor.db.from('community_resources').select('*',{count:'exact',head:true}).eq('status','pending'),actor.db.from('content_entries').select('*',{count:'exact',head:true}).eq('status','published').gt('published_at',new Date().toISOString()).is('deleted_at',null),actor.db.from('contact_submissions').select('*',{count:'exact',head:true}).eq('resolved',false)]);return <AdminShell module="dashboard" role={actor.role} email={actor.email}><div className="admin-top"><div><p className="eyebrow">TESC CONTENT MANAGEMENT</p><h1>管理總覽</h1><p>整理內容，與教會及讀者同行。</p></div></div><div className="admin-stats"><article><p>待審核資源</p><strong>{pending??'—'}</strong><Link className="text-link" href="/admin/resources">審核文件 →</Link></article><article><p>已排程內容</p><strong>{scheduled??'—'}</strong><Link className="text-link" href="/admin/prayer">管理代禱信 →</Link></article><article><p>未處理查詢</p><strong>{contacts??'—'}</strong><Link className="text-link" href="/admin/contacts">查看收件匣 →</Link></article></div><section className="admin-panel" style={{marginTop:28}}><h2>開始編輯</h2><p className="muted">每項內容均可獨立輸入繁體中文、簡體中文及英文。排程日期以香港時間輸入，儲存後會在指定時間公開。</p><div className="admin-toolbar"><Link className="button" href="/admin/prayer">新增代禱信</Link><Link className="button secondary" href="/admin/video">管理介紹片</Link><Link className="button secondary" href="/admin/media">上載媒體</Link></div></section></AdminShell>}
