'use client';
import {useEffect,useState,useCallback} from 'react';
import {modules} from '@/lib/modules';
import {type Entry,type Media,type Resource,type Role,type Locale,locales,i18n,visible} from '@/lib/domain';
import {ContentEditor} from './content-editor';
type Contact={id:string;name:string;email:string;phone:string;subject:string;message:string;created_at:string;delivery_status:string;resolved:boolean};
type Profile={id:string;role:Role;display_name:string};
async function api<T>(url:string,method='GET',body?:unknown):Promise<T>{const res=await fetch(url,{method,headers:body?{'content-type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const data=await res.json();if(!res.ok)throw new Error(data.error||'未能完成操作。');return data;}
export function AdminApp({module,role}:{module:string;role:Role}){const config=modules.find(m=>m.key===module)!;const [items,setItems]=useState<Entry[]>([]),[media,setMedia]=useState<Media[]>([]),[resources,setResources]=useState<Resource[]>([]),[contacts,setContacts]=useState<Contact[]>([]),[profiles,setProfiles]=useState<Profile[]>([]),[references,setReferences]=useState<Entry[]>([]),[resourceEdit,setResourceEdit]=useState<Resource|null>(null),[resourceLocale,setResourceLocale]=useState<Locale>('zh-Hant'),[editing,setEditing]=useState<Entry|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[progress,setProgress]=useState(0);
 const load=useCallback(async()=>{setLoading(true);try{if(config.kind){const [data,m]=await Promise.all([api<Entry[]>(`/api/admin/content?kind=${config.kind}`),api<Media[]>('/api/admin/media')]);setItems(config.group?data.filter(e=>e.data.person_group===config.group):data);setMedia(m);if(config.kind==='ministry'||config.kind==='course')setReferences(await api<Entry[]>(`/api/admin/content?kind=${config.kind==='ministry'?'course':'course_category'}`));}else if(module==='media')setMedia(await api<Media[]>('/api/admin/media'));else if(module==='resources')setResources(await api<Resource[]>('/api/admin/resources'));else if(module==='contacts')setContacts(await api<Contact[]>('/api/admin/contacts'));else if(module==='roles')setProfiles(await api<Profile[]>('/api/admin/roles'));}catch(e){setMessage((e as Error).message);}finally{setLoading(false);}},[config.kind,config.group,module]);
 useEffect(()=>{void load();},[load]);
 async function act(fn:()=>Promise<unknown>,success='已儲存。'){setBusy(true);setMessage('');try{await fn();setMessage(success);await load();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 function create(){const p={kind:config.kind!,slug:config.kind==='settings'?'site':config.kind==='contact'?'contact':config.kind==='donation'?'default':'',title:i18n('','',''),description:i18n('','',''),body:i18n('','',''),data:config.group?{person_group:config.group as 'staff'|'board'}:{},status:'draft' as const,published_at:null,display_order:items.length,featured:false,is_demo:false,is_private:false};setEditing(p as Entry);}
 async function save(p:Entry){await act(async()=>{await api('/api/admin/content','POST',p);setEditing(null);});}
 async function upload(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const data=new FormData(form);setBusy(true);setMessage('');setProgress(0);try{await new Promise<void>((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('POST','/api/admin/media');xhr.upload.onprogress=e=>{if(e.lengthComputable)setProgress(Math.round(e.loaded/e.total*100));};xhr.onload=()=>{if(xhr.status>=200&&xhr.status<300)resolve();else{try{reject(new Error(JSON.parse(xhr.responseText).error));}catch{reject(new Error('未能上載檔案。'));}}};xhr.onerror=()=>reject(new Error('連線中斷，請重試。'));xhr.send(data);});form.reset();setMessage('已上載。檔案通過安全檢查並被已發佈內容使用後，才會公開。');await load();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 const status=(p:Entry)=>p.status==='published'?visible(p)?'published':'scheduled':p.status;
 return <><div className="admin-top"><div><p className="eyebrow">TESC / CONTENT MANAGEMENT</p><h1>{config.label}</h1></div>{config.kind&&!editing&&<button className="button" onClick={create}>＋ 新增內容</button>}</div>{message&&<p role="status" className="notice admin-message">{message}</p>}{loading&&<p role="status">載入中…</p>}{editing?<ContentEditor initial={editing} media={media} references={references} busy={busy} onClose={()=>setEditing(null)} onSave={save}/>:config.kind?<div className="table-scroll"><table className="admin-table"><thead><tr><th>標題</th><th>狀態</th><th>次序</th><th>操作</th></tr></thead><tbody>{items.map((p,i)=><tr key={p.id}><td>{p.title['zh-Hant']||p.title.en||'（未命名）'}{p.is_demo&&<small> · DEMO</small>}</td><td><span className={`status-badge ${status(p)}`}>{{published:'已發佈',scheduled:'已排程',draft:'草稿',archived:'已封存'}[status(p)]}</span></td><td>{p.display_order}<button disabled={busy||i===0} aria-label="上移" onClick={()=>void act(async()=>{await api('/api/admin/content','POST',{...p,display_order:items[i-1].display_order});await api('/api/admin/content','POST',{...items[i-1],display_order:p.display_order});})}>↑</button></td><td><button onClick={()=>setEditing(p)}>編輯／預覽</button><button onClick={()=>setEditing({...p,id:undefined as unknown as string,slug:`${p.slug}-copy-${Date.now().toString(36)}`,status:'draft',published_at:null})}>複製</button><button disabled={busy} onClick={()=>void act(()=>api('/api/admin/content','POST',{...p,status:p.status==='published'?'draft':'published',published_at:new Date().toISOString()}))}>{p.status==='published'?'取消發佈':'立即發佈'}</button><button disabled={busy} onClick={()=>void act(()=>api('/api/admin/content','POST',{...p,status:'archived'}))}>封存</button><button disabled={busy} onClick={()=>{if(window.confirm('確定移除這項內容？內容將隱藏並保留於資料庫，可由管理員還原。'))void act(()=>api('/api/admin/content','DELETE',{id:p.id}),'內容已移除。');}}>刪除</button></td></tr>)}</tbody></table>{!loading&&!items.length&&<div className="empty-admin">尚未有內容。按「新增內容」開始。</div>}</div>:null}
 {module==='media'&&<><form className="admin-panel" onSubmit={upload}><h2>上載／更換檔案</h2><p className="muted">PDF、JPG、PNG、WebP、MP4。更換時請上載新檔案，再於內容編輯器選取；舊檔案不會被覆寫。</p><label className="field">檔案<input type="file" name="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.mp4" required/></label><label className="field">分類<input name="category" maxLength={100}/></label><button className="button" disabled={busy}>上載檔案</button>{busy&&<><progress className="progress" max={100} value={progress}/><p role="status">上載 {progress}% · 正在處理及安全檢查</p></>}</form><div className="media-grid">{media.map(m=><article className="media-card" key={m.id}>{m.mime_type.startsWith('image/')?<img src={`/api/media/${m.id}`} alt={m.original_name}/>:<div className="empty-state">{m.mime_type==='video/mp4'?'MP4':'PDF'}</div>}<h3>{m.original_name}</h3><span className="meta">{(m.file_size/1024/1024).toFixed(1)} MB · {m.category}</span><span className="status-badge">安全檢查：{m.scan_status}</span><div className="admin-toolbar"><a className="text-link" href={`/api/media/${m.id}`} target="_blank" rel="noreferrer">預覽 ↗</a><button onClick={()=>void navigator.clipboard.writeText(`${window.location.origin}/api/media/${m.id}`).then(()=>setMessage('已複製網址。'))}>複製網址</button><button disabled={busy} onClick={()=>void act(()=>api('/api/admin/media','PATCH',{id:m.id,action:'rescan'}))}>重新掃描</button>{role==='super_admin'&&m.scan_status!=='clean'&&<button disabled={busy} onClick={()=>{if(window.confirm('只有已使用可信防毒工具完成掃描，並確認檔案安全，才可繼續。此確認將記錄於稽核紀錄。是否已完成外部掃描？'))void act(()=>api('/api/admin/media','PATCH',{id:m.id,action:'verify-clean'}));}}>確認外部掃描</button>}<button disabled={busy} onClick={()=>{if(window.confirm('確定永久刪除此檔案？正在使用的檔案不能刪除。'))void act(()=>api('/api/admin/media','DELETE',{id:m.id}),'檔案已刪除。');}}>刪除</button></div></article>)}</div></>}
 {module==='resources'&&resourceEdit&&<form className="admin-panel" onSubmit={e=>{e.preventDefault();void act(async()=>{await api('/api/admin/resources','PATCH',{id:resourceEdit.id,title:resourceEdit.title,description:resourceEdit.description,category:resourceEdit.category});setResourceEdit(null);});}}><h2>編輯資源資料</h2><div className="admin-toolbar">{locales.map(l=><button type="button" key={l} aria-pressed={l===resourceLocale} onClick={()=>setResourceLocale(l)}>{l}</button>)}</div><label className="field">標題<input value={resourceEdit.title[resourceLocale]||''} onChange={e=>setResourceEdit({...resourceEdit,title:{...resourceEdit.title,[resourceLocale]:e.target.value}})}/></label><label className="field">簡介<textarea value={resourceEdit.description[resourceLocale]||''} onChange={e=>setResourceEdit({...resourceEdit,description:{...resourceEdit.description,[resourceLocale]:e.target.value}})}/></label><label className="field">分類代稱<input value={resourceEdit.category} onChange={e=>setResourceEdit({...resourceEdit,category:e.target.value})}/></label><button className="button" disabled={busy}>儲存資料</button><button className="button secondary" type="button" onClick={()=>setResourceEdit(null)}>取消</button></form>}{module==='resources'&&<div className="table-scroll"><table className="admin-table"><thead><tr><th>資源／提供者（私密）</th><th>審核／安全檢查</th><th>操作</th></tr></thead><tbody>{resources.map(r=><tr key={r.id}><td>{r.title['zh-Hant']||r.title['zh-Hans']||r.title.en}<p className="meta">{r.contributor_name} · {r.contributor_email}</p><p>{r.description['zh-Hant']||r.description['zh-Hans']||r.description.en}</p></td><td>{r.status} / {r.scan_status}</td><td><button onClick={()=>setResourceEdit(r)}>編輯資料</button><a className="text-link" href={`/api/media/${r.media_id}`} target="_blank" rel="noreferrer">查看 PDF ↗</a><button disabled={busy||r.scan_status!=='clean'} onClick={()=>void act(()=>api('/api/admin/resources','PATCH',{id:r.id,status:'approved',published:true}),'資源已批准並公開。')}>批准並公開</button><button disabled={busy} onClick={()=>void act(()=>api('/api/admin/resources','PATCH',{id:r.id,status:'rejected',published:false}))}>拒絕</button><button disabled={busy} onClick={()=>void act(()=>api('/api/admin/resources','PATCH',{id:r.id,status:'hidden',published:false}))}>隱藏</button></td></tr>)}</tbody></table>{!loading&&!resources.length&&<div className="empty-admin">目前沒有待審核文件。</div>}</div>}
 {module==='contacts'&&<div className="admin-contacts">{contacts.map(c=><article key={c.id} className="admin-panel"><h2>{c.subject}</h2><p>{c.name} · {c.email} · {c.phone}</p><p className="meta">{new Date(c.created_at).toLocaleString('zh-HK',{timeZone:'Asia/Hong_Kong'})} · 電郵通知：{c.delivery_status}</p><pre>{c.message}</pre><button className="button secondary" disabled={busy} onClick={()=>void act(()=>api('/api/admin/contacts','PATCH',{id:c.id,resolved:!c.resolved}))}>{c.resolved?'標記未處理':'標記已處理'}</button></article>)}{!loading&&!contacts.length&&<div className="empty-admin">目前沒有查詢。</div>}</div>}
 {module==='roles'&&<><form className="admin-panel" onSubmit={e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.currentTarget));void act(()=>api('/api/admin/roles','POST',p));}}><h2>新增／更新管理員權限</h2><p>先在 Supabase Auth 邀請使用者，再輸入其 User ID。此網站不開放管理員註冊。</p><label className="field">Supabase User ID<input name="id" required/></label><label className="field">顯示名稱<input name="display_name" required/></label><label className="field">角色<select name="role"><option value="editor">編輯</option><option value="super_admin">主管理員</option></select></label><button className="button" disabled={busy}>儲存權限</button></form><div className="table-scroll"><table className="admin-table"><thead><tr><th>管理員</th><th>角色</th><th>操作</th></tr></thead><tbody>{profiles.map(p=><tr key={p.id}><td>{p.display_name}<p className="meta">{p.id}</p></td><td>{p.role}</td><td><button disabled={busy} onClick={()=>{if(window.confirm('確定移除此使用者的管理權限？'))void act(()=>api('/api/admin/roles','DELETE',{id:p.id}));}}>移除權限</button></td></tr>)}</tbody></table></div></>}
 </>;
}
