import {entries,mediaUrl} from '@/lib/content';
import {type Locale,translation} from '@/lib/domain';
import {Translated} from './public';

type Copy=[string,string,string];
const t=(value:Copy,locale:Locale)=>value[locale==='en'?2:locale==='zh-Hans'?1:0];
const courses:{year:number;term:Copy;title:Copy;teacher:Copy;summary:Copy}[]=[
 {year:2024,term:['春季','春季','Spring'],title:['基督教倫理學','基督教伦理学','Christian Ethics'],teacher:['梁家麟院長','梁家麟院长','Dr Leung Ka-lun'],summary:['從基督信仰出發，透過十堂課思考倫理判斷與生活實踐。','从基督信仰出发，透过十堂课思考伦理判断与生活实践。','Ten lessons on ethical discernment and everyday practice from a Christian perspective.']},
 {year:2024,term:['春季','春季','Spring'],title:['健康教會','健康教会','Healthy Church'],teacher:['蘇穎智牧師','苏颖智牧师','Rev Su Wing-chi'],summary:['探討健康教會的特質，以及如何在地方教會中實踐。','探讨健康教会的特质，以及如何在地方教会中实践。','Explores the marks of a healthy church and their application in local congregations.']},
 {year:2024,term:['秋季','秋季','Autumn'],title:['舊約歷史','旧约历史','Old Testament History'],teacher:['甘汝誠老師','甘汝诚老师','Kam Yu-shing'],summary:['梳理舊約歷史脈絡，幫助學員在背景中閱讀經文。','梳理旧约历史脉络，帮助学员在背景中阅读经文。','Surveys the historical setting of the Old Testament to support informed reading.']},
 {year:2024,term:['秋季','秋季','Autumn'],title:['新約概論（一）','新约概论（一）','New Testament Survey I'],teacher:['梁作榮牧師','梁作荣牧师','Rev Leung Chok-wing'],summary:['介紹四福音書和使徒行傳，建立研讀新約的基礎。','介绍四福音书和使徒行传，建立研读新约的基础。','Introduces the four Gospels and Acts as a foundation for New Testament study.']},
 {year:2025,term:['春季','春季','Spring'],title:['創世人生：創世記研讀','创世人生：创世记研读','Genesis: Life and Beginnings'],teacher:['吳健暉牧師','吴健晖牧师','Rev Ng Kin-fai'],summary:['以引導問題研讀創世記，適合個人反思與小組討論。','以引导问题研读创世记，适合个人反思与小组讨论。','A guided study of Genesis designed for personal reflection and group discussion.']},
 {year:2025,term:['春季','春季','Spring'],title:['青少年精神與情緒健康','青少年精神与情绪健康','Youth Mental and Emotional Health'],teacher:['樊翠玲、吳詠茵','樊翠玲、吴咏茵','Fan Tsui-ling and Ng Wing-yan'],summary:['幫助陪伴青少年的同工辨識常見困擾、學習關懷技巧，並善用社區資源。','帮助陪伴青少年的同工辨识常见困扰、学习关怀技巧，并善用社区资源。','Helps youth workers recognise common mental health concerns, practise care and use community resources.']},
 {year:2025,term:['秋季','秋季','Autumn'],title:['召命人生','召命人生','A Life of Calling'],teacher:['黃天逸牧師','黄天逸牧师','Rev Wong Tin-yat'],summary:['從聖經人物的回應出發，反思個人召命、生命成長與服侍方向。','从圣经人物的回应出发，反思个人召命、生命成长与服侍方向。','Reflects on biblical responses to God’s call, personal growth and the direction of service.']},
 {year:2025,term:['秋季','秋季','Autumn'],title:['實用釋經學','实用释经学','Practical Hermeneutics'],teacher:['吳健暉牧師','吴健晖牧师','Rev Ng Kin-fai'],summary:['學習基本釋經原則、聖經文學類型及經文應用，並配合實踐練習。','学习基本释经原则、圣经文学类型及经文应用，并配合实践练习。','Covers core interpretation methods, biblical genres and practical application.']},
 {year:2026,term:['春季','春季','Spring'],title:['成聖之旅：事奉人員品格成長','成圣之旅：事奉人员品格成长','Journey of Sanctification'],teacher:['林海虹博士','林海虹博士','Dr Lam Hoi-hung'],summary:['省察服侍中的價值取向與生命品格，透過學習與反思調整事奉方向。','省察服侍中的价值取向与生命品格，透过学习与反思调整事奉方向。','Examines values and character in ministry through study and reflection.']},
 {year:2026,term:['春季','春季','Spring'],title:['婚姻輔導','婚姻辅导','Marriage Counselling'],teacher:['黃天逸牧師','黄天逸牧师','Rev Wong Tin-yat'],summary:['以系統思維和依附理論，建立婚姻輔導的實務框架與基本技巧。','以系统思维和依附理论，建立婚姻辅导的实务框架与基本技巧。','Builds a practical counselling framework using systems thinking and attachment theory.']},
 {year:2026,term:['秋季','秋季','Autumn'],title:['證道學','证道学','Homiletics'],teacher:['吳健暉牧師','吴健晖牧师','Rev Ng Kin-fai'],summary:['從聽道與講道的態度開始，學習講章準備及不同講道方法。','从听道与讲道的态度开始，学习讲章准备及不同讲道方法。','Introduces sermon preparation, preaching approaches and the attitudes of speaker and listener.']},
 {year:2026,term:['秋季','秋季','Autumn'],title:['現代宣教學','现代宣教学','Contemporary Missiology'],teacher:['駱瑞鳳博士','骆瑞凤博士','Dr Lok Sui-fung'],summary:['回顧普世宣教的發展，思考信徒與教會如何在當代參與宣教。','回顾普世宣教的发展，思考信徒与教会如何在当代参与宣教。','Traces developments in world mission and explores participation by individuals and churches today.']}
];
const work:{title:Copy;summary:Copy}[]=[
 {title:['跨國教學合作','跨国教学合作','Teaching across borders'],summary:['2025年與意大利華人神學院深化合作：春季及秋季派教師赴意大利授課，同年完成四科網上課程的錄製。','2025年与意大利华人神学院深化合作：春季及秋季派教师赴意大利授课，同年完成四科网上课程的录制。','In 2025, TESC sent teachers to Italy in spring and autumn and recorded four online courses with the Italian Chinese Theological Seminary.']},
 {title:['網上學習與資源製作','网上学习与资源制作','Online learning and media'],summary:['優化 Co-Sunday 網上教學平台，整合影片服務及字幕製作，支援不同地區學員觀看課程；亦協助更新神學院網站及信仰影片。','优化 Co-Sunday 网上教学平台，整合影片服务及字幕制作，支援不同地区学员观看课程；亦协助更新神学院网站及信仰影片。','The team improved the Co-Sunday learning platform, video delivery and subtitles for learners across regions, while supporting website updates and faith-based videos.']},
 {title:['教會與領袖培訓','教会与领袖培训','Church and leader training'],summary:['2025年在歐洲多地及香港教會安排講道、培靈聚會和領袖訓練，並探討差傳與科技牧養等主題。','2025年在欧洲多地及香港教会安排讲道、培灵聚会和领袖训练，并探讨差传与科技牧养等主题。','In 2025, TESC served churches in Europe and Hong Kong through preaching, spiritual formation and leadership training, including mission and technology in pastoral care.']},
 {title:['神學資源與後勤支援','神学资源与后勤支援','Resources and practical support'],summary:['協助意大利華人神學院的畢業典禮與教材物資，並整理及運送約30箱捐贈圖書往意大利，讓教學資源能繼續流通。','协助意大利华人神学院的毕业典礼与教材物资，并整理及运送约30箱捐赠图书往意大利，让教学资源能继续流通。','The team supported the seminary’s graduation and teaching materials, and sorted and sent around 30 donated boxes of books to Italy.']}
];
export async function PosterGallery({locale}:{locale:Locale}){
 const posters=await entries('poster');
 const view=t(['查看原海報','查看原海报','View original poster'],locale);
 return <>
  <section id="courses" className="curriculum-section"><div className="curriculum-heading"><div><p className="eyebrow">LEARNING PATHWAY</p><h2>{t(['十二科網上神學課程','十二科网上神学课程','Twelve-course theology pathway'],locale)}</h2><p>{t(['與意大利華人神學院合作的三年制普通話網上文憑延伸課程，以錄製課堂配合教會小組討論，裝備信徒領袖在信仰、品格與教會服侍上成長。','与意大利华人神学院合作的三年制普通话网上文凭延伸课程，以录制课堂配合教会小组讨论，装备信徒领袖在信仰、品格与教会服侍上成长。','A three-year Mandarin online diploma extension programme with the Italian Chinese Theological Seminary. Recorded lessons and church-based group discussion help equip lay leaders in faith, character and service.'],locale)}</p></div><div className="curriculum-metrics"><div><strong>12</strong><span>{t(['科課程','科课程','courses'],locale)}</span></div><div><strong>36</strong><span>{t(['學分','学分','credits'],locale)}</span></div><div><strong>3–6</strong><span>{t(['年修讀期','年修读期','years of study'],locale)}</span></div></div></div>
  <div className="curriculum-tracks"><article><span>{t(['4 科課程','4 科课程','4 COURSES'],locale)}</span><h3>{t(['核心必修','核心必修','Core studies'],locale)}</h3><p>{t(['由召命、品格與釋經出發，建立事奉與靈命的基礎。','由召命、品格与释经出发，建立事奉与灵命的基础。','Foundations in calling, character and biblical interpretation.'],locale)}</p></article><article><span>{t(['4 科課程','4 科课程','4 COURSES'],locale)}</span><h3>{t(['聖經神學選修','圣经神学选修','Bible and theology'],locale)}</h3><p>{t(['按需要研讀舊約、新約及神學專題。','按需要研读旧约、新约及神学专题。','Electives in Old and New Testament study and theological themes.'],locale)}</p></article><article><span>{t(['4 科課程','4 科课程','4 COURSES'],locale)}</span><h3>{t(['教會事工選修','教会事工选修','Church ministry'],locale)}</h3><p>{t(['涵蓋教會生活、青少年關懷與婚姻輔導等實際課題。','涵盖教会生活、青少年关怀与婚姻辅导等实际课题。','Practical topics including church life, youth care and marriage counselling.'],locale)}</p></article></div>
  <div className="curriculum-sources"><p>{t(['以下海報記錄2024–2026年的課程安排；海報上的報名日期與收費屬當時資料。','以下海报记录2024–2026年的课程安排；海报上的报名日期与收费属当时资料。','These posters document the 2024–2026 course schedule. Their registration dates and fees are historical.'],locale)}</p><div><a href="/images/courses.jpeg" target="_blank" rel="noreferrer">{t(['閱覽課程簡介海報','阅览课程简介海报','View programme overview poster'],locale)} ↗</a><a href="/images/diploma-structure.jpeg" target="_blank" rel="noreferrer">{t(['閱覽學分與課程編排','阅览学分与课程编排','View credits and schedule poster'],locale)} ↗</a></div></div></section>
  <section id="posters" className="poster-section"><div className="showcase-heading"><div><p className="eyebrow">COURSE ARCHIVE · 2024–2026</p><h2>{t(['課程主題與海報','课程主题与海报','Courses and their posters'],locale)}</h2></div><p>{t(['每科附有內容摘要；按海報可查看原圖。','每科附有内容摘要；点击海报可查看原图。','Read each course summary alongside its original poster.'],locale)}</p></div>
   {[2024,2025,2026].map(year=><div className="course-year" key={year}><h3>{year}</h3><div className="course-cards">{courses.filter(course=>course.year===year).map(course=>{const i=courses.indexOf(course);const src=`/images/poster-${String(i+1).padStart(3,'0')}.${i<8?'jpg':'jpeg'}`;return <article className="course-card" key={src}><a className="course-card-image" href={src} target="_blank" rel="noreferrer" aria-label={`${t(course.title,locale)} — ${view}`}><img loading="lazy" src={src} alt={t(course.title,locale)}/></a><div className="course-card-copy"><p className="meta">{year} · {t(course.term,locale)}</p><h4>{t(course.title,locale)}</h4><p>{t(course.summary,locale)}</p><p className="course-teacher">{t(['講師','讲师','Lecturer'],locale)} · {t(course.teacher,locale)}</p><a href={src} target="_blank" rel="noreferrer">{view} ↗</a></div></article>})}</div></div>)}
   {posters.length>0&&<div className="community-posters"><h3>{t(['更多課程及事工資訊','更多课程及事工资讯','More courses and ministry updates'],locale)}</h3><div className="course-cards">{posters.map(p=><article className="course-card" key={p.id}>{p.data.image_id&&<a className="course-card-image" href={mediaUrl(p.data.image_id)} target="_blank" rel="noreferrer"><img loading="lazy" src={mediaUrl(p.data.image_id)} alt={translation(p.title,locale).text}/></a>}<div className="course-card-copy"><h4><Translated value={p.title} locale={locale}/></h4><p><Translated value={p.description} locale={locale}/></p>{p.data.image_id&&<a href={mediaUrl(p.data.image_id)} target="_blank" rel="noreferrer">{view} ↗</a>}</div></article>)}</div></div>}
  </section>
  <section id="ministry-work" className="ministry-work"><div className="showcase-heading"><div><p className="eyebrow">2025 MINISTRY REPORT</p><h2>{t(['課堂以外的服侍','课堂以外的服侍','Service beyond the classroom'],locale)}</h2></div><p>{t(['根據本團2025年事工報告整理。','根据本团2025年事工报告整理。','A summary of TESC’s 2025 ministry report.'],locale)}</p></div><div className="work-grid">{work.map((item,i)=><article key={i}><span>{String(i+1).padStart(2,'0')}</span><h3>{t(item.title,locale)}</h3><p>{t(item.summary,locale)}</p></article>)}</div></section>
 </>;
}
