'use client';
import {useRef,useState,useEffect} from 'react';
import {dict} from '@/lib/i18n';
import type {Locale} from '@/lib/domain';
type Turnstile={render:(el:HTMLElement,options:Record<string,unknown>)=>string;reset:(id:string)=>void;remove:(id:string)=>void};
declare global {interface Window {turnstile?:Turnstile}}
export function PublicForm({type,locale,siteKey,limit=10,categories=[]}:{type:'resource'|'contact';locale:Locale;siteKey:string;limit?:number;categories?:{id:string;label:string}[]}){const d=dict(locale),widget=useRef<HTMLDivElement>(null),widgetId=useRef<string|undefined>(undefined);const [busy,setBusy]=useState(false),[status,setStatus]=useState(''),[ok,setOk]=useState(false);
 useEffect(()=>{if(!siteKey)return;let active=true;const mount=()=>{if(active&&widget.current&&window.turnstile&&widgetId.current===undefined)widgetId.current=window.turnstile.render(widget.current,{sitekey:siteKey,action:type,language:locale==='en'?'en':locale==='zh-Hans'?'zh-cn':'zh-tw'});};let script=document.querySelector<HTMLScriptElement>('script[data-turnstile]');if(!script){script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.async=true;script.dataset.turnstile='true';document.head.appendChild(script);}script.addEventListener('load',mount);mount();return()=>{active=false;script?.removeEventListener('load',mount);if(widgetId.current&&window.turnstile)window.turnstile.remove(widgetId.current);widgetId.current=undefined;};},[siteKey,type,locale]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setBusy(true);setOk(false);setStatus('');try{const result=await fetch(type==='resource'?'/api/resources':'/api/contact',{method:'POST',body:new FormData(form)});if(!result.ok){setStatus(result.status===503?d.unavailable:d.formError);return;}setOk(true);setStatus(type==='resource'?d.uploadSuccess:d.sendSuccess);form.reset();}catch{setStatus(d.formError);}finally{setBusy(false);if(widgetId.current)window.turnstile?.reset(widgetId.current);}}
 return <form onSubmit={submit} className="public-form"><input type="hidden" name="locale" value={locale}/><div className="honeypot" aria-hidden="true"><label>Website<input name="website" tabIndex={-1} autoComplete="off"/></label></div>{type==='contact'?<><div className="form-grid"><label>{d.name}<input name="name" required maxLength={120} autoComplete="name"/></label><label>{d.email}<input type="email" name="email" required maxLength={254} autoComplete="email"/></label></div><label>{d.phone}<input name="phone" maxLength={50} autoComplete="tel"/></label><label>{d.subject}<input name="subject" required maxLength={200}/></label><label>{d.message}<textarea name="message" required minLength={10} maxLength={10000} rows={5}/></label><label className="check"><input name="consent" type="checkbox" required/>{d.consent}</label><p className="small muted">{d.privacy}</p></>:<><p className="muted">{d.pending}</p><label>{d.title}<input name="title" required minLength={2} maxLength={200}/></label><label>{d.description}<textarea name="description" required minLength={5} maxLength={3000} rows={4}/></label><label>{d.category}<select name="category"><option value="general">{d.general}</option>{categories.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label><label>{d.file}<input type="file" name="file" accept="application/pdf,.pdf" required/><small>{d.pdfLimit} {limit} MB</small></label><div className="form-grid"><label>{d.contributor}<input name="contributor_name" maxLength={120}/></label><label>{d.optionalEmail}<input type="email" name="contributor_email" maxLength={254}/></label></div><label className="check"><input name="agreement" type="checkbox" required/>{d.agreement}</label></>}<div ref={widget}/>{!siteKey&&<p className="notice">{d.unavailable}</p>}<button disabled={busy||!siteKey} className="button" type="submit">{busy?d.sending:d.submit}</button><p role="status" className={ok?'success':'error-text'}>{status}</p></form>;
}
