import Link from 'next/link';
import {ArrowUpRight,FileText,BookOpen,ArrowRight} from 'lucide-react';
import {type Locale,type I18n,type Entry,translation,videoEmbed} from '@/lib/domain';
import {dict,date,monthDate} from '@/lib/i18n';
import {cleanHtml} from '@/lib/sanitize';
import {mediaUrl} from '@/lib/content';
export function Translated({value,locale,rich=false}:{value?:I18n;locale:Locale;rich?:boolean}){const t=translation(value,locale);if(!t.text)return null;return <>{t.fallback&&<small className="fallback">{locale==='en'?'Available language':locale==='zh-Hans'?'现有语言':'現有語言'}：{{'zh-Hant':'繁體中文','zh-Hans':'简体中文',en:'English'}[t.language]}</small>}{rich?<div lang={t.language} className="prose" dangerouslySetInnerHTML={{__html:cleanHtml(t.text)}}/>:<span lang={t.language}>{t.text}</span>}</>}
export function PageHero({eyebrow,title,description,archive=false}:{eyebrow:string;title:string;description?:string;archive?:boolean}){return <section className={`page-hero ${archive?'archive-hero':''}`}><div className="wrap"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{description&&<p className="lead">{description}</p>}</div>{archive&&<span className="archive-mark" aria-hidden="true">文獻<br/>記憶</span>}</section>}
export function Empty({children,icon='book'}:{children:React.ReactNode;icon?:'book'|'file'}){return <div className="empty-state">{icon==='book'?<BookOpen size={26} strokeWidth={1}/>:<FileText size={26} strokeWidth={1}/>}<p>{children}</p></div>}
export function SectionTitle({n,title,en,href,label}:{n?:string;title:string;en?:string;href?:string;label?:string}){return <div className="section-title"><div>{n&&<p className="eyebrow">{n} / {en}</p>}<h2>{title}</h2></div>{href&&<Link className="text-link" href={href}>{label}<ArrowUpRight size={18}/></Link>}</div>}
export function EntryCard({item,locale,base}:{item:Entry;locale:Locale;base:string}){return <article className="entry-card">{item.data.image_id&&<img loading="lazy" src={mediaUrl(item.data.image_id)} alt={translation(item.title,locale).text}/>}<div>{item.is_demo&&<span className="tag">DEMO / PLACEHOLDER</span>}{item.kind==='prayer'&&<p className="meta">{item.data.author} · {item.published_at&&(item.data.timeline_date?monthDate(item.published_at,locale):date(item.published_at,locale))}{item.is_private?(locale==='en'?' · Members only':locale==='zh-Hans'?' · 会员专享':' · 會員專享'):''}</p>}{item.kind==='project_document'&&<p className="meta">{item.data.category||'文獻'} · {item.data.project_status==='completed'?'已完成':'進行中'} · {item.published_at&&date(item.published_at,locale)}{item.is_private?(locale==='en'?' · Members only':locale==='zh-Hans'?' · 会员专享':' · 會員專享'):''}</p>}<h3><Link href={`${base}/${item.slug}`}><Translated value={item.title} locale={locale}/></Link></h3><p><Translated value={item.description} locale={locale}/></p><Link className="text-link" href={`${base}/${item.slug}`}>{dict(locale).learn}<ArrowRight size={16}/></Link></div></article>}
export function TeamTeaser({people,locale}:{people:Entry[];locale:Locale}){if(!people.length)return null;return <section className="section wrap"><SectionTitle n="02" en="OUR PEOPLE" title={dict(locale).team} href={`/${locale}/team`} label={dict(locale).learn}/><div className="people-grid">{people.map(p=><article className="person" key={p.id}>{p.data.image_id?<img src={mediaUrl(p.data.image_id)} alt={translation(p.title,locale).text}/>:['leung','fai'].includes(p.slug)?<img src={`/images/${p.slug==='leung'?'dr-leung':'fai'}.avif`} alt={translation(p.title,locale).text}/>:<div className="portrait-placeholder">JOYCE</div>}<h3><Translated value={p.title} locale={locale}/></h3><p><Translated value={p.data.role} locale={locale}/></p><p><Translated value={p.data.biography||p.description} locale={locale}/></p></article>)}</div></section>}
export function Video({item,locale}:{item?:Entry;locale:Locale}){const d=dict(locale);if(!item)return <div className="video-empty"><span className="play-outline">▷</span><p>{d.videoEmpty}</p></div>;const title=translation(item.title,locale).text;if(item.data.source_type==='upload')return <figure><video className="ministry-video" controls preload="none" poster={mediaUrl(item.data.poster_id)||undefined} aria-label={title} src={mediaUrl(item.data.video_id)}><track kind="captions"/></video><figcaption>{title}</figcaption><Translated value={item.body} locale={locale} rich/></figure>;const url=videoEmbed(item.data.source_type||'',item.data.video_url||'');return url?<figure><iframe className="ministry-video" loading="lazy" src={url} title={title} allowFullScreen referrerPolicy="strict-origin-when-cross-origin"/><figcaption>{title}</figcaption><Translated value={item.body} locale={locale} rich/></figure>:<Empty>{d.videoEmpty}</Empty>}
